finish
rshekula/AQA_MTS_RSH pull request #11
Opened 2023-12-24 16:00 UTC by rshekula

2023-12-26 09:41 UTC, wildpioneer requested changes

2023-12-26 09:41 UTC, wildpioneer commented on Strings/one.cs
> +            string none = one.ToLower(); // подогнал всё под нижний регистр, чтобы поменялись все слова test (кроме 4)
Как вариант - но не совсем верное решение. Посмотри лекцию по строкам, мы там говорили про параметр, который и отвечает за учитывать или нет регистр

2023-12-26 09:52 UTC, rshekula commented on Strings/one.cs
> +            string none = one.ToLower(); // подогнал всё под нижний регистр, чтобы поменялись все слова test (кроме 4)
Да, я его как раз пытался использовать, но что-то не получилось совместить. И некорректно отрабатывал код.

2023-12-27 09:44 UTC, rshekula commented
Изменил код 1 задания. Добавил параметр игнорирования регистра.

2024-01-29 10:13 UTC, wildpioneer commented
Проверено

2024-01-29 10:13 UTC, closed without merging