Types and operators hw
rshekula/AQA_MTS_RSH pull request #6
Opened 2023-12-11 15:17 UTC by rshekula

New pull request
First work

2023-12-26 09:26 UTC, wildpioneer requested changes

2023-12-26 09:26 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +                else
Тут лучше использовать структуру else if - меньше строчек кода будет

2023-12-26 09:26 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +            int result = number % 2;
:) Ну нет - это просто синтаксически другой вариант, а не функциональный - там второй вариант с побитовым или используется... Если интересно погугли

2023-12-26 09:58 UTC, rshekula commented on TypesAndOperators/Program.cs
> +                else
да, я попытался прописать else if, но видимо где-то ошибся, т.к. некорректно работало. 
поэтому выбрал такой вариант, в котором был уверен

2023-12-26 09:59 UTC, rshekula commented on TypesAndOperators/Program.cs
> +            int result = number % 2;
Обязательно загуглю, Спасибо!

2023-12-26 14:22 UTC, rshekula reviewed
отредактировал 2 кейс с else if

2024-01-29 10:14 UTC, wildpioneer commented
Проверено

2024-01-29 10:14 UTC, closed without merging