Arrays hw
rshekula/AQA_MTS_RSH pull request #8
Opened 2023-12-12 16:44 UTC by rshekula

Finish

2023-12-26 09:39 UTC, wildpioneer requested changes

2023-12-26 09:39 UTC, wildpioneer commented on Arrays/HW2.cs
> +                    number[i] = 0;
Это не совсем удаление - это ты просто заменил значение

2023-12-26 09:39 UTC, wildpioneer commented on Arrays/HW2.cs
> +                foreach (int play2 in number)
Так он же не новый - а старый - просто с немного другими значениями - а новый массив явно будет короче по размеру, если удаляемое число присутствует в нем

2023-12-26 09:54 UTC, rshekula commented on Arrays/HW2.cs
> +                    number[i] = 0;
Да, у меня почему-то именно во второй задаче возникли сложности с подменой. Поэтому некоторые решения были уже как желание найти хоть какой-то выход.

2023-12-27 09:16 UTC, rshekula commented
Исправил 2 кейс. Теперь число удаляется из массива

2024-01-29 10:14 UTC, wildpioneer commented
Проверено

2024-01-29 10:14 UTC, closed without merging